export const GET_USERS = 'GET_USERS'
export const SET_LOADING = 'SET_LOADING'
export const USERS_ERROR = 'USERS_ERROR'
export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'